### ISSUE TITLE
Bug: Traceback when trying to download sticker packs, mising 'packKey'

### ISSUE THREAD

**Issue by tastytea** [FHPythonUtils/SigStickers#1]
## Bug

- [x] I have read the comment above and have completed each step
- [x] I have filled out the system info
- [x] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### System info

- OS: Linux [hostname] 5.10.76-gentoo-r1-x86_64 #1 SMP [date & time] x86_64 AMD A10-9700 […] GNU/Linux
- Version: Don't know, installed it with `pip` 5 minutes ago

### Describe the bug

I installed with `pip install --user sigstickers`.

When I run `python -m sigstickers`, I get this output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tastytea/.local/lib/python3.9/site-packages/sigstickers/__main__.py", line 6, in <module>
    cli()
  File "/home/tastytea/.local/lib/python3.9/site-packages/sigstickers/__init__.py", line 23, in cli
    packs = sum(args.pack, [])
TypeError: 'NoneType' object is not iterable
```

When I run `python -m sigstickers -p https://signalstickers.com/pack/8669f77e790bf2d73b67d03a67092f77` , I get this output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tastytea/.local/lib/python3.9/site-packages/sigstickers/__main__.py", line 6, in <module>
    cli()
  File "/home/tastytea/.local/lib/python3.9/site-packages/sigstickers/__init__.py", line 33, in cli
    asyncio.run(convertPack(*asyncio.run(downloadPack(*packAttrs))))
TypeError: downloadPack() missing 1 required positional argument: 'packKey'
```

### Expected outcome

Downloaded sticker-pack.

### Actual outcome

Error message.

**Comment by FredHappyface** [comment]
Hi 

Unfortunately the pack key is required: eg `https://signal.art/addstickers/#pack_id=9acc9e8aba563d26a4994e69263e3b25&pack_key=5a6dff3948c28efb9b7aaf93ecc375c69fc316e78077ed26867a14d10a0f6a12` 

However, I do need to improve the error messages - I'll get to work on that 

Hope this makes sense

**Comment by tastytea** [comment]
I did not realize I had to use the link from the “Add to Signal” button. Thank you!

**Comment by FredHappyface** [comment]
No worries, cheers for the issue - working on some more user-friendly errors now :)
