### ISSUE TITLE
`TypeError: color must be int or single-element tuple`

### ISSUE THREAD

**Issue by sewnie** [FHPythonUtils/SigStickers#4]
```
/home/sewn/src/SigStickers/venv/lib/python3.12/site-packages/PIL/Image.py:1056: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/sewn/src/SigStickers/sigstickers/__main__.py", line 5, in <module>
    cli()
  File "/home/sewn/src/SigStickers/sigstickers/cli.py", line 38, in cli
    sysexit(main(packs))
            ^^^^^^^^^^^
  File "/home/sewn/src/SigStickers/sigstickers/cli.py", line 57, in main
    asyncio.run(convert_pack(*downloaded))
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/sewn/src/SigStickers/sigstickers/downloader.py", line 168, in convert_pack
    converted_files.append(converted.result())
                           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sewn/src/SigStickers/sigstickers/downloader.py", line 127, in convert_with_pil
    img.save(
  File "/home/sewn/src/SigStickers/venv/lib/python3.12/site-packages/PIL/Image.py", line 2568, in save
    save_handler(self, fp, filename)
  File "/home/sewn/src/SigStickers/venv/lib/python3.12/site-packages/PIL/GifImagePlugin.py", line 737, in _save_all
    _save(im, fp, filename, save_all=True)
  File "/home/sewn/src/SigStickers/venv/lib/python3.12/site-packages/PIL/GifImagePlugin.py", line 750, in _save
    if not save_all or not _write_multiple_frames(im, fp, palette):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sewn/src/SigStickers/venv/lib/python3.12/site-packages/PIL/GifImagePlugin.py", line 663, in _write_multiple_frames
    background_im = Image.new("P", im_frame.size, background)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sewn/src/SigStickers/venv/lib/python3.12/site-packages/PIL/Image.py", line 3102, in new
    return im._new(core.fill(mode, size, color))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: color must be int or single-element tuple
```
Sticker pack contains animated stickers.

**Comment by FredHappyface** [comment]
Sorry cannot replicate this locally. What pack is it you are attempting to convert? If you're not happy sharing over here, can you plonk an email to alarmcuddly@outlook.com. Cheers :)

**Comment by FredHappyface** [comment]
definitely fixed in 2025

instead of crashing completely, you'll get a log line with "Failed to save {input_file} as gif"

It would still be beneficial to understand waht sticker/ pack causes this if you can :)
